config/routes.rb
Rails.application.routes.draw do
  root to: 'coins#index'
  
  resources :coins, only: [] do
    post 'mark', on: :member
    post 'erase_markings', on: :collection
  end
  
  resources :distributions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
require 'open-uri'

class Coin < ApplicationRecord
  scope :favorite, -> { where(marked: true) }
  
  def self.fetch_all(max_pages: 999)
    parse_page("https://coinmarketcap.com/1", pages_parsed: 0, max_pages: max_pages)
  rescue OpenURI::HTTPError
    puts "No more pages left."
  end
  
  def self.parse_page(url, pages_parsed:, max_pages:)
    return if pages_parsed == max_pages
    
    page = Nokogiri::HTML open(url)
    
    page.css("table#currencies tbody > tr").each do |currency|
      Coin.create(
        name: currency.css(".currency-name-container").text,
        ticker: currency.css(".currency-symbol a").text,
        marketcap: currency.css("td.market-cap").attr("data-usd").text.to_f,
        price: currency.css(".price[data-usd]").attr("data-usd").text.to_f,
        supply: currency.css("[data-supply]").attr("data-supply").text.to_f)
    end
    
    pages_parsed += 1
    
    next_page_url = "https://coinmarketcap.com/#{pages_parsed+1}"
    parse_page(next_page_url, pages_parsed: pages_parsed, max_pages: max_pages)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :default_params
  
  def index
    @coins = Coin.where('marketcap > 0 and supply > 0').order('marketcap desc')
    @coins = @coins.where("marketcap < #{params[:marketcap]}*1000000 and supply < #{params[:supply]}*1000000 and price < #{params[:price]}")
  end
  
  def mark
    @coin = Coin.find(params[:id])
    if @coin.in? selected_coins
      set_selected_coins selected_coins.where.not(id: @coin)
    else
      set_selected_coins selected_coins + [@coin]
    end
  end
  
  def erase_markings
    Coin.where(marked: true).update_all(marked: false)
    redirect_to root_path
  end
  
  private
  
    def default_params
      params[:marketcap] ||= 500
      params[:supply] ||= 200
      params[:price] ||= 0.7
    end
    
    def selected_coins
      Coin.where id: session[:selected_coins]&.split(",")
    end
    
    def set_selected_coins coins
      session[:selected_coins] = coins.collect(&:id).join(",")
    end
    
    helper_method :selected_coins
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  def new
    @coins = Coin.where(marked: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def arrow
    image_tag "arrow.svg", class: "arrow"
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
  def huge_number(number)
    number_to_human(number, units: {:million => "M", :billion => "B"})
  end
  
  
  def numerical_param_field(name, options = {})
    number_field_tag name, params[name]
  end
end

app/helpers/distribution_helper.rb
module DistributionHelper
end

app/views/application/_heading.html.erb
<h2>Redditor's Interactive Guide to Underappreciated Altcoins</h2>
<div class="subheading">by <%= link_to "chayblay", "https://www.reddit.com/r/altcoin/comments/7ophbu/how_do_i_actually_find_coins_before_theyre/dsbnane/", target: :blank %> and <%= link_to "your's truly", "https://www.reddit.com/user/colorfulfool", target: :blank %></div>

app/views/coins/_coins_table.html.erb
<table>
  <tr>
    <th></th>
    <th>Market cap</th>
    <th>Price, $</th>
    <th>Supply</th>
  </tr>

  <tbody>
    <% @coins.each do |coin| %>
      <tr data-coin="<%= coin.id %>">
        <td><%= coin.name %> <%= link_to coin.ticker, mark_coin_path(coin), method: :post, remote: true %></td>
        <td><%= huge_number coin.marketcap %></td>
        <td><%= number_to_currency coin.price, unit: '' %></td>
        <td><%= huge_number coin.supply %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/coins/_favorites_table.html.erb
<table>
  <caption>Seleted coins</caption>
  
  <% selected_coins.each do |coin| %>
    <tr data-coin="<%= coin.id %>">
      <td><%= coin.name %> <%= link_to coin.ticker, mark_coin_path(coin), method: :post, remote: true %></td>
      <td><%= number_to_currency coin.price %></td>
    </tr>
  <% end %>
</table>


<%= arrow %>

<p class="commentary">
  Read the coin white paper and see if it solves, or at least aims to solve, a real world problem.
</p>

<p class="commentary">
  Read the team bios to look for all-star members.
</p>

<%= arrow %>

<p class="commentary">
  If you like the coin, then do some Technical Analysis on its price action, both short term and long term, and draw trend lines.<br><br> TA will help you find buying and selling zones for entries and exits, but most importantly it will give you what you should refer to from now on as your system for risk management (i.e. stop losses).
</p>

app/views/coins/_filters.html.erb
<%= form_with url: root_path, method: :get, remote: true, id: "filters_form" do |form| %>
  Market cap < <%= numerical_param_field :marketcap %> M and
  Supply < <%= numerical_param_field :supply %> M and
  Price < <%= numerical_param_field :price %>
<% end %>

app/views/coins/index.html.erb
<div class="padded introduction">
  <%= render "heading" %>

  <p class="commentary">Look for coins with <$500M market cap and a circulating supply <200M, check to see a cheap price per coin, etc.</p>
  <%= render "filters" %>
  
  <p id="found_coins">Found <%= pluralize @coins.count, "coin" %>. Click on tickers to select.</p>
</div>

<div class="columns-inside">
  <div id="coins_table">
    <%= render "coins_table" %>
  </div>
  
  <div id="favorites_table">
    <%= render "favorites_table" %>
  </div>
</div>

app/views/coins/index.js.erb
document.querySelector('#coins_table').innerHTML = "<%=j render 'coins_table' %>"

loadingFinished("Found <%= pluralize @coins.count, 'coin' %>. Click on tickers to select.")

app/views/coins/mark.js.erb
document.querySelectorAll('<%= "[data-coin=\"#{@coin.id}\"]".html_safe %>').forEach(function (coinRow) { 
  coinRow.style.background = "<%= @coin.marked ? '#EDAFB8' : '#EF626C' %>"
  setTimeout(function () { coinRow.style.background = 'white'; }, 200)
})


document.querySelector('#favorites_table').innerHTML = "<%=j render 'favorites_table' %>"

app/views/distributions/new.html.erb
<div class="padded">
  <h3 style="margin-top: 0px" contenteditable>Distribution</h3>
  
  <input name="amount" value="0.1" /> <span contenteditable name="distributionCurrency">ETH</span>
  representing $<input name="dollarAmount" value="100" />
</div>

<table>
  <% @coins.each do |coin| %>
    <tr data-coin="<%= coin.id %>">
      <td class="checkbox"><input type="checkbox" /></td>
      <td><%= coin.name %> <%= link_to coin.ticker, mark_coin_path(coin), method: :post, remote: true %></td>
      <td name="dollarShare">$25</td>
      <td name="share"></td>
      <td name="exchange" style="color: lightgray">
        <span contenteditable>???</span>
      </td>
    </tr>
  <% end %>
</table>

<div class="padded">
  Selected: <span name="selectedTotal">0</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditor's Interactive Guide to Altcoins</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>